services:
  app:
    image: ghcr.io/jeufore/sonos-youtube-cast:latest
    environment:
      # Required
      - SONOS_DEVICE_IP=192.168.1.100        # Your Sonos device IP address
      # Optional
      - DEVICE_NAME=My YouTube Cast Receiver  # Name shown in cast devices list
      - LOG_LEVEL=info                        # debug, info, warn, error
      - MEETUBE_API_BASE_URL=http://metube:8081
      - MEETUBE_AUDIO_URL=http://<service_ip>:8081/audio_download
      - PLAYLIST_PULL_INTERVAL=30             # Seconds between playlist updates
      - PLAYLIST_MAX_AHEAD_DOWNLOAD=10        # Number of tracks to download ahead
      - PLAYLIST_DOWNLOAD_INTERVAL=20         # Seconds between downloads
    network_mode: host
    volumes:
      - ./node-persist:/usr/src/app/.node-persist
    restart: unless-stopped
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube
    ports:
      - 8081:8081
    environment:
      # Optional
      - STATE_DIR=/data
      - AUDIO_DOWNLOAD_DIR=/musics
      - DEFAULT_OPTION_PLAYLIST_ITEM_LIMIT=10
      - OUTPUT_TEMPLATE=%(artist|Unknown)s/%(album|Unknown)s/%(track)s.%(ext)s
    volumes:
      - ./data/metube:/data
      - ./downloads/metube:/downloads
      # Optional: to persist downloaded music files
      - ./musics:/musics
    restart: unless-stopped